# Import the camera server
from cscore import CameraServer
# Import OpenCV and NumPy
import cv2
import numpy
import math
from enum import Enum
import traceback
from networktables import NetworkTablesInstance
import time as tm
import RPi.GPIO as GPIO
import json
from cscore import CameraServer, VideoSource, UsbCamera, MjpegServer
import threading
import sys


class GripPipeline:
    """
    An OpenCV pipeline generated by GRIP.
    """
    
    def __init__(self):
        """initializes all values to presets or None if need to be set
        """

        self.__hsl_threshold_hue = [65.0, 129.0]
        self.__hsl_threshold_saturation = [201.0, 255.0]
        self.__hsl_threshold_luminance = [53.0, 196.0]

        self.hsl_threshold_output = None

        self.__find_contours_input = self.hsl_threshold_output
        self.__find_contours_external_only = False

        self.find_contours_output = None

        self.__filter_contours_contours = self.find_contours_output
        self.__filter_contours_min_area = 3.0
        self.__filter_contours_min_perimeter = 0.0
        self.__filter_contours_min_width = 50.0
        self.__filter_contours_max_width = 1000.0
        self.__filter_contours_min_height = 30.0
        self.__filter_contours_max_height = 1000.0
        self.__filter_contours_solidity = [0, 100]
        self.__filter_contours_max_vertices = 1000000.0
        self.__filter_contours_min_vertices = 0.0
        self.__filter_contours_min_ratio = 0.0
        self.__filter_contours_max_ratio = 1000.0

        self.filter_contours_output = None


    def process(self, source0):
        """
        Runs the pipeline and sets all outputs to new values.
        """
        # Step HSL_Threshold0:
        self.__hsl_threshold_input = source0
        (self.hsl_threshold_output) = self.__hsl_threshold(self.__hsl_threshold_input, self.__hsl_threshold_hue, self.__hsl_threshold_saturation, self.__hsl_threshold_luminance)

        # Step Find_Contours0:
        self.__find_contours_input = self.hsl_threshold_output
        (self.find_contours_output) = self.__find_contours(self.__find_contours_input, self.__find_contours_external_only)

        # Step Filter_Contours0:
        self.__filter_contours_contours = self.find_contours_output
        (self.filter_contours_output) = self.__filter_contours(self.__filter_contours_contours, self.__filter_contours_min_area, self.__filter_contours_min_perimeter, self.__filter_contours_min_width, self.__filter_contours_max_width, self.__filter_contours_min_height, self.__filter_contours_max_height, self.__filter_contours_solidity, self.__filter_contours_max_vertices, self.__filter_contours_min_vertices, self.__filter_contours_min_ratio, self.__filter_contours_max_ratio)


    @staticmethod
    def __hsl_threshold(input, hue, sat, lum):
        """Segment an image based on hue, saturation, and luminance ranges.
        Args:
            input: A BGR numpy.ndarray.
            hue: A list of two numbers the are the min and max hue.
            sat: A list of two numbers the are the min and max saturation.
            lum: A list of two numbers the are the min and max luminance.
        Returns:
            A black and white numpy.ndarray.
        """
        out = cv2.cvtColor(input, cv2.COLOR_BGR2HLS)
        return cv2.inRange(out, (hue[0], lum[0], sat[0]),  (hue[1], lum[1], sat[1]))

    @staticmethod
    def __find_contours(input, external_only):
        """Sets the values of pixels in a binary image to their distance to the nearest black pixel.
        Args:
            input: A numpy.ndarray.
            external_only: A boolean. If true only external contours are found.
        Return:
            A list of numpy.ndarray where each one represents a contour.
        """
        if(external_only):
            mode = cv2.RETR_EXTERNAL
        else:
            mode = cv2.RETR_LIST
        method = cv2.CHAIN_APPROX_SIMPLE
        im2, contours, hierarchy =cv2.findContours(input, mode=mode, method=method)
        return contours

    @staticmethod
    def __filter_contours(input_contours, min_area, min_perimeter, min_width, max_width,
                        min_height, max_height, solidity, max_vertex_count, min_vertex_count,
                        min_ratio, max_ratio):
        """Filters out contours that do not meet certain criteria.
        Args:
            input_contours: Contours as a list of numpy.ndarray.
            min_area: The minimum area of a contour that will be kept.
            min_perimeter: The minimum perimeter of a contour that will be kept.
            min_width: Minimum width of a contour.
            max_width: MaxWidth maximum width.
            min_height: Minimum height.
            max_height: Maximimum height.
            solidity: The minimum and maximum solidity of a contour.
            min_vertex_count: Minimum vertex Count of the contours.
            max_vertex_count: Maximum vertex Count.
            min_ratio: Minimum ratio of width to height.
            max_ratio: Maximum ratio of width to height.
        Returns:
            Contours as a list of numpy.ndarray.
        """
        output = []
        for contour in input_contours:
            x,y,w,h = cv2.boundingRect(contour)
            if (w < min_width or w > max_width):
                continue
            if (h < min_height or h > max_height):
                continue
            area = cv2.contourArea(contour)
            if (area < min_area):
                continue
            if (cv2.arcLength(contour, True) < min_perimeter):
                continue
            hull = cv2.convexHull(contour)
            solid = 100 * area / cv2.contourArea(hull)
            if (solid < solidity[0] or solid > solidity[1]):
                continue
            if (len(contour) < min_vertex_count or len(contour) > max_vertex_count):
                continue
            ratio = (float)(w) / h
            if (ratio < min_ratio or ratio > max_ratio):
                continue
            output.append(contour)
        return output





configFile = "/boot/frc.json"

class CameraConfig: pass

team = None
server = False
cameraConfigs = []
switchedCameraConfigs = []
cameras = []

def parseError(str):
    """Report parse error."""
    print("config error in '" + configFile + "': " + str, file=sys.stderr)

def readCameraConfig(config):
    """Read single camera configuration."""
    cam = CameraConfig()

    # name
    try:
        cam.name = config["name"]
    except KeyError:
        parseError("could not read camera name")
        return False

    # path
    try:
        cam.path = config["path"]
    except KeyError:
        parseError("camera '{}': could not read path".format(cam.name))
        return False

    # stream properties
    cam.streamConfig = config.get("stream")

    cam.config = config

    cameraConfigs.append(cam)
    return True

def readSwitchedCameraConfig(config):
    """Read single switched camera configuration."""
    cam = CameraConfig()

    # name
    try:
        cam.name = config["name"]
    except KeyError:
        parseError("could not read switched camera name")
        return False

    # path
    try:
        cam.key = config["key"]
    except KeyError:
        parseError("switched camera '{}': could not read key".format(cam.name))
        return False

    switchedCameraConfigs.append(cam)
    return True

def readConfig():
    """Read configuration file."""
    global team
    global server

    # parse file
    try:
        with open(configFile, "rt", encoding="utf-8") as f:
            j = json.load(f)
    except OSError as err:
        print("could not open '{}': {}".format(configFile, err), file=sys.stderr)
        return False

    # top level must be an object
    if not isinstance(j, dict):
        parseError("must be JSON object")
        return False

    # team number
    try:
        team = j["team"]
    except KeyError:
        parseError("could not read team number")
        return False

    # ntmode (optional)
    if "ntmode" in j:
        str = j["ntmode"]
        if str.lower() == "client":
            server = False
        elif str.lower() == "server":
            server = True
        else:
            parseError("could not understand ntmode value '{}'".format(str))

    # cameras
    try:
        cameras = j["cameras"]
    except KeyError:
        parseError("could not read cameras")
        return False
    for camera in cameras:
        if not readCameraConfig(camera):
            return False

    # switched cameras
    if "switched cameras" in j:
        for camera in j["switched cameras"]:
            if not readSwitchedCameraConfig(camera):
                return False

    return True

def startCamera(config):
    """Start running the camera."""
    print("Starting camera '{}' on {}".format(config.name, config.path))
    inst = CameraServer.getInstance()
    camera = UsbCamera(config.name, config.path)
    server = inst.startAutomaticCapture(camera=camera, return_server=True)

    camera.setConfigJson(json.dumps(config.config))
    camera.setConnectionStrategy(VideoSource.ConnectionStrategy.kKeepOpen)

    if config.streamConfig is not None:
        server.setConfigJson(json.dumps(config.streamConfig))

    return camera

def startSwitchedCamera(config):
    """Start running the switched camera."""
    print("Starting switched camera '{}' on {}".format(config.name, config.key))
    server = CameraServer.getInstance().addSwitchedCamera(config.name)

    def listener(fromobj, key, value, isNew):
        if isinstance(value, float):
            i = int(value)
            if i >= 0 and i < len(cameras):
              server.setSource(cameras[i])
        elif isinstance(value, str):
            for i in range(len(cameraConfigs)):
                if value == cameraConfigs[i].name:
                    server.setSource(cameras[i])
                    break

    NetworkTablesInstance.getDefault().getEntry(config.key).addListener(
        listener,
        ntcore.constants.NT_NOTIFY_IMMEDIATE |
        ntcore.constants.NT_NOTIFY_NEW |
        ntcore.constants.NT_NOTIFY_UPDATE)

    return server




def main(ntinst):

    ledControlPin = 18

    dutyCycle = 30
    configFile = "/boot/frc.json"

    GPIO.setmode( GPIO.BCM )

    GPIO.setup( ledControlPin, GPIO.OUT )
    pwm = GPIO.PWM( ledControlPin, 150 )
    pwm.start( 0 )
    pwm.ChangeDutyCycle( dutyCycle )




    #cam = readCameraConfig( camConfig )
    #startCamera( cam )

    cs = CameraServer.getInstance()

    #cs.enableLogging()

    # Capture from the first USB Camera on the system

    #width  = 1280 / 2
    #height = 720 / 2

    width  = 320
    height = 240





    #camera = cs.startAutomaticCapture()
    #camera.set
    #camera.setResolution(width, height)
    # Get a CvSink. This will capture images from the camera
    #camera.setExposureManual(10); 
    #camera.getProperty( 'saturation' ).set( 100 )

    #print( camera.getConfigJson() )  

    cvSink = cs.getVideo()
    # (optional) Setup a CvSource. This will send images back to the Dashboard

    outputStream = cs.putVideo("Name", width, height)
    # Allocating new images is very expensive, always try to preallocate

    pipeline = GripPipeline()

    tm.sleep(1)

    xCoordTable   = ntinst.getTable( 'targetCoords' )
    timesTable    = ntinst.getTable( 'loopTimes' )
    ledStateTable = ntinst.getTable( 'ledState' )
    #xCoordValue = xCoordTable.getEntry( 'val' )
    #print( dir( xCoordTable ) )

    img = numpy.zeros(shape=(height, width, 3), dtype=numpy.uint8)

    numLoopTimes = 10
    loopTimes    = [ 0 for a in range( numLoopTimes ) ]
    processTimes = [ 0 for a in range( numLoopTimes ) ]
    grabTimes    = [ 0 for a in range( numLoopTimes ) ]
    idx = 0
    lastLoopTime = tm.time()

    lastLedTime = tm.time()
    ledOn = False

    while True:
      #tm.sleep(1000)
      #continue

      try:
          beforeGrab =  tm.time()
          time, img = cvSink.grabFrame(img)
          afterGrab =  tm.time()
          if time == 0:
              xCoordTable.putNumber( 'xVal', -1 )
              xCoordTable.putNumber( 'yVal', -1 )
              # Send the output the error.
              outputStream.notifyError(cvSink.getError());
              # skip the rest of the current iteration
              continue


          pipeline.process( img ) 
          afterProcess =  tm.time()

          #grabTimes[idx]    = afterGrab - beforeGrab
          #processTimes[idx] = afterProcess - afterGrab

          #idx += 1

          #cv2.drawContours( pipeline.hsl_threshold_output, pipeline.filter_contours_output, -1, (0, 255, 0), 3 )
          print( 'contours:', len( pipeline.filter_contours_output ) )
          if len( pipeline.filter_contours_output ) > 0:

              if True:
                cv2.drawContours( 
                    img, 
                    pipeline.filter_contours_output, 
                    -1, 
                    (0, 0, 255),
                    3 
                )
              #print( len(pipeline.find_contours_output) )
              try:
                  #print( len(pipeline.find_contours_output) )
                  #print( pipeline.filter_contours_output )
                  rect = cv2.minAreaRect( pipeline.find_contours_output[0] )

                  box = cv2.boxPoints(rect)
                  box2 = numpy.int0( box )
                  #print( rect  )
                  #print( box   )
                  #print( 'Orig' )
                  #print( box2  )
                  #print( type( box2[0][0] ) )
                  #print( dir( xCoordValue ) )
                  #xCoordValue.putNumber( ( rect[0] + rect[2] ) / 2 )


                  rect = cv2.boundingRect( pipeline.filter_contours_output[0] )
                  box  = ( (           float(rect[0]),           float(rect[1]) ), 
                           (           float(rect[0]), float(rect[1] + rect[3]) ),
                           ( float(rect[0] + rect[2]), float(rect[1] + rect[3]) ),
                           ( float(rect[0] + rect[2]),           float(rect[1]) ),
                           )
                  box2 = numpy.int0( box )

                  #print( 'rect: {}'.format( box2 ) )
                  #print( box2[0][0] )
                  #print( box2[2][0] )



                  numToPut = ( box2[0][0] + box2[2][0] ) / 2
                  #print( 'numToPut: {}'.format( numToPut ) )
                  xCoordTable.putNumber( 'xVal', numToPut )

                  numToPut2 = ( box2[0][1] + box2[2][1] ) / 2
                  xCoordTable.putNumber( 'yVal', numToPut2 )

                  print('found:',numToPut,numToPut2)
                  #print( type( rect ) )
                  #print( type( box ) )

                  #print( rect )
                  #print( box )
                  #print( 'New' )
                  #print( box2 )
                  #print( type( box2[0][0] ) )




              except:
                  xCoordTable.putNumber( 'xVal', -1 )
                  xCoordTable.putNumber( 'yVal', -1 )
                  print( traceback.format_exc() )
                  tm.sleep(1)


          else:
              print( 'No Contours' )
              xCoordTable.putNumber( 'xVal', -1 )
              xCoordTable.putNumber( 'yVal', -1 )
              center = ( int(width / 2), int(height / 2) )
       
              cv2.circle(
                  img,
                  center,
                  int(width / 20),
                  (255, 0, 0),
                  int(3),
                  int(8)
              )

          #outputStream.putFrame( pipeline.hsl_threshold_output )

          outputStream.putFrame( img )
      except:
        print( 'No Contours' )
        xCoordTable.putNumber( 'xVal', -1 )
        xCoordTable.putNumber( 'yVal', -1 )
        print( 'Main try block:' )
        print( traceback.format_exc() )

if __name__ == '__main__':


    if len(sys.argv) >= 2:
        configFile = sys.argv[1]

    # read configuration
    if not readConfig():
        sys.exit(1)

    # start NetworkTables
    ntinst = NetworkTablesInstance.getDefault()
    if server:
        print("Setting up NetworkTables server")
        ntinst.startServer()
    else:
        print("Setting up NetworkTables client for team {}".format(team))
        ntinst.startClientTeam(team)

    # start cameras
    for config in cameraConfigs:
        cameras.append(startCamera(config))

    # start switched cameras
    #for config in switchedCameraConfigs:
    #    startSwitchedCamera(config)








    # start NetworkTables
    #ntinst = NetworkTablesInstance.getDefault()

    #server = False
    #team = 2227
    #if server:
    #    print("Setting up NetworkTables server")
    #    ntinst.startServer()
    #else:
    #    print("Setting up NetworkTables client for team {}".format(team))
    #    ntinst.startClientTeam(team)

    main(ntinst)
